language: python
cache:
   directories:
     - $HOME/.cache/pre-commit
python:
  - "3.7.1"
install:
  - pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
before_script:
  - pre-commit run --all-files
  - mypy .
script:
  - pytest
